VAGRANTFILE_API_VERSION = "2"

# set provider to use
ENV["VAGRANT_DEFAULT_PROVIDER"] = "libvirt"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :jeos_sle12_build do |jeos_sle12_build|
    jeos_sle12_build.vm.box = "kiwi-build-box"

    if ENV["VAGRANT_DEFAULT_PROVIDER"] == "libvirt"
      # LibVirt
      jeos_sle12_build.vm.provider :libvirt do |domain|
        domain.memory = 2048
        domain.cpus = 1
        domain.nested = true
      end
    else
      # VirtualBox
      jeos_sle12_build.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
      end
    end
  end
end
