VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :jeos_sle12_build do |jeos_sle12_build|
    jeos_sle12_build.vm.box = "kiwi-build-box"
    jeos_sle12_build.vm.provider :virtualbox do |domain|
      domain.memory = 1024
      domain.cpus = 1
      domain.nested = false
      domain.volume_cache = 'none'
    end
  end
end
