VAGRANTFILE_API_VERSION = "2"

ENV["VAGRANT_DEFAULT_PROVIDER"] = "libvirt"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :buildbox do |buildbox|
    buildbox.vm.box = "kiwi-build-box"

    buildbox.vm.provider :libvirt do |domain|
      domain.memory = 1024
      domain.cpus = 1
      domain.nested = false
      domain.volume_cache = 'none'
    end
  end

end


