VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :jeos_13_1_build do |jeos_13_1_build|
    jeos_13_1_build.vm.box = "kiwi-build-box"

    jeos_13_1_build.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
    end
  end
end
