VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :jeos_sle12_build do |jeos_sle12_build|
    jeos_sle12_build.vm.box = "kiwi-build-box"

    jeos_sle12_build.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end
end
